import { Nunito } from 'next/font/google';
import "./globals.css";
import MainContextWrapper from '@/components/ContextApi/MainContext';


const nunito = Nunito({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased bg-[#EFF4F4]`}
      >
        <MainContextWrapper>
          {children}
        </MainContextWrapper>
      </body>
    </html>
  );
}
